server:
  port: 8001
spring:
  application:
    name: cloud-provide-hystrix-payment
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true #表示像注册中心服务注册自己
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/


