server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.235.107:8848 #Nacos的地址
        #server-addr: localhost:8848 #Nacos的地址
management:
  endpoints:
    web:
      exposure:
        include: '*'